---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: voting
spec:
  resources:
    - {type: git, name: api-repo}
    - {type: image, name: api-image}
    - {type: git, name: ui-repo}
    - {type: image, name: ui-image}

  tasks:
    # pipeline
    # (build-api) -> deploy-api
    #                        \
    # (build-ui) ------------->---> deploy-ui

    ### api ###
    - name: build-api
      taskRef:
        name: s2i-go
      resources:
        inputs:
          - {name: source, resource: api-repo}
        outputs:
          - {name: image, resource: api-image}
      params:
        - {name: TLSVERIFY, value: "false"}

    - name: apply-api-manifests
      taskRef:
        name: apply-manifests
      resources:
        inputs:
          - {name: source, resource: api-repo}
      runAfter:
        - build-api

    - name: update-api-image
      taskRef:
        name: update-deployment
      resources:
        inputs:
          - {name: image, resource: api-image}
      params:
        - {name: deployment, value: api}
      runAfter:
        - apply-api-manifests

    - name: build-ui
      taskRef: {name: s2i-python-3}
      resources:
        inputs:
          - {name: source, resource: ui-repo}
        outputs:
          - {name: image, resource: ui-image}
      params:
        - {name: TLSVERIFY, value: "false"}

    - name: deploy-ui
      taskRef:
        name: apply-manifests
      resources:
        inputs:
          - {name: source, resource: ui-repo}
          - {name: image, resource: ui-image}
      params:
        - {name: deployment, value: ui}
      runAfter:
        - deploy-api
        - build-ui
